// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izrebfzyrdpjnoneclhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6cmViZnp5cmRwam5vbmVjbGhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODYxOTksImV4cCI6MjA3MzI2MjE5OX0.FGGDtAFGKoNhLbHAz2DvkQHScIcG5FdY3-tw4_EW7IM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});